services:
  fasttasks_database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fasttasks_app:
    image: fasttasks_app
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY} 
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}  
    command: sh -c "wait-for-it fasttasks_database:5432 --timeout=30 -- alembic upgrade head && uvicorn fast_tasks.app:app --host 0.0.0.0 --port 8000"
    depends_on:
      fasttasks_database:
        condition: service_healthy
volumes:
  pgdata: